# Site settings
title: Warehouse # site title
description: >- # site description
  Just Chunbong <a href="https://github.com/Chunbon9" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Asia/Seoul # set your timezone
image: assets/img/profile.png # This image used for Open Graph more info https://ogp.me/
repo: # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Chunbong # author name
  bio: >- # tell to the world
    <a href="mailto:jms2141@naver.com" target="_blank" rel="noopener">jms2141@naver.com</a> <a href="https://github.com/ChunBon9" target="_blank" rel="noopener">@github</a>.
  username: chunbong # general username
  github: ChunBon9 # github username
  twitter: # twitter username
  facebook: # facebook username
  email: jms2141@naver.com # email adress
  avatar: assets/img/profile.png # change with your own avatar

# URL settings
url: "https:/chunbon9.github.io" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
